//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceSerecu
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://tempuri.org/")]
    public partial class Persona : object
    {
        
        private string celula_identidadField;
        
        private string nombresField;
        
        private string primer_apellidoField;
        
        private string segundo_apellidoField;
        
        private string fecha_nacimientoField;
        
        private string sexoField;
        
        private string estado_civilField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string celula_identidad
        {
            get
            {
                return this.celula_identidadField;
            }
            set
            {
                this.celula_identidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombres
        {
            get
            {
                return this.nombresField;
            }
            set
            {
                this.nombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string primer_apellido
        {
            get
            {
                return this.primer_apellidoField;
            }
            set
            {
                this.primer_apellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string segundo_apellido
        {
            get
            {
                return this.segundo_apellidoField;
            }
            set
            {
                this.segundo_apellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fecha_nacimiento
        {
            get
            {
                return this.fecha_nacimientoField;
            }
            set
            {
                this.fecha_nacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sexo
        {
            get
            {
                return this.sexoField;
            }
            set
            {
                this.sexoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string estado_civil
        {
            get
            {
                return this.estado_civilField;
            }
            set
            {
                this.estado_civilField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CertificadoDeNacimiento", Namespace="http://tempuri.org/")]
    public partial class CertificadoDeNacimiento : object
    {
        
        private string cedula_identidadField;
        
        private string nombresField;
        
        private string primer_apellidoField;
        
        private string segundo_apellidoField;
        
        private string fecha_nacimientoField;
        
        private string nombre_padreField;
        
        private string apellidos_padreField;
        
        private string nombre_madreField;
        
        private string apellidos_madreField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string cedula_identidad
        {
            get
            {
                return this.cedula_identidadField;
            }
            set
            {
                this.cedula_identidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombres
        {
            get
            {
                return this.nombresField;
            }
            set
            {
                this.nombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string primer_apellido
        {
            get
            {
                return this.primer_apellidoField;
            }
            set
            {
                this.primer_apellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string segundo_apellido
        {
            get
            {
                return this.segundo_apellidoField;
            }
            set
            {
                this.segundo_apellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fecha_nacimiento
        {
            get
            {
                return this.fecha_nacimientoField;
            }
            set
            {
                this.fecha_nacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string nombre_padre
        {
            get
            {
                return this.nombre_padreField;
            }
            set
            {
                this.nombre_padreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string apellidos_padre
        {
            get
            {
                return this.apellidos_padreField;
            }
            set
            {
                this.apellidos_padreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string nombre_madre
        {
            get
            {
                return this.nombre_madreField;
            }
            set
            {
                this.nombre_madreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string apellidos_madre
        {
            get
            {
                return this.apellidos_madreField;
            }
            set
            {
                this.apellidos_madreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="certificadoMatrimonio", Namespace="http://tempuri.org/")]
    public partial class certificadoMatrimonio : object
    {
        
        private string cedula_identidadField;
        
        private string cedula_identidad_esposoField;
        
        private string nombre_esposoField;
        
        private string primerapellido_esposoField;
        
        private string segundoapellido_esposoField;
        
        private string cedula_identidad_esposaField;
        
        private string nombre_esposaField;
        
        private string primerapellido_esposaField;
        
        private string segundoapellido_esposaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string cedula_identidad
        {
            get
            {
                return this.cedula_identidadField;
            }
            set
            {
                this.cedula_identidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string cedula_identidad_esposo
        {
            get
            {
                return this.cedula_identidad_esposoField;
            }
            set
            {
                this.cedula_identidad_esposoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre_esposo
        {
            get
            {
                return this.nombre_esposoField;
            }
            set
            {
                this.nombre_esposoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string primerapellido_esposo
        {
            get
            {
                return this.primerapellido_esposoField;
            }
            set
            {
                this.primerapellido_esposoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string segundoapellido_esposo
        {
            get
            {
                return this.segundoapellido_esposoField;
            }
            set
            {
                this.segundoapellido_esposoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string cedula_identidad_esposa
        {
            get
            {
                return this.cedula_identidad_esposaField;
            }
            set
            {
                this.cedula_identidad_esposaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string nombre_esposa
        {
            get
            {
                return this.nombre_esposaField;
            }
            set
            {
                this.nombre_esposaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string primerapellido_esposa
        {
            get
            {
                return this.primerapellido_esposaField;
            }
            set
            {
                this.primerapellido_esposaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string segundoapellido_esposa
        {
            get
            {
                return this.segundoapellido_esposaField;
            }
            set
            {
                this.segundoapellido_esposaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CertificadoDefuncion", Namespace="http://tempuri.org/")]
    public partial class CertificadoDefuncion : object
    {
        
        private string cedula_identidadField;
        
        private string nombresField;
        
        private string primer_apellidoField;
        
        private string segundo_apellidoField;
        
        private string fecha_defuncionField;
        
        private string causaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string cedula_identidad
        {
            get
            {
                return this.cedula_identidadField;
            }
            set
            {
                this.cedula_identidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombres
        {
            get
            {
                return this.nombresField;
            }
            set
            {
                this.nombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string primer_apellido
        {
            get
            {
                return this.primer_apellidoField;
            }
            set
            {
                this.primer_apellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string segundo_apellido
        {
            get
            {
                return this.segundo_apellidoField;
            }
            set
            {
                this.segundo_apellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fecha_defuncion
        {
            get
            {
                return this.fecha_defuncionField;
            }
            set
            {
                this.fecha_defuncionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string causa
        {
            get
            {
                return this.causaField;
            }
            set
            {
                this.causaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceSerecu.SerecuWebServiceSoap")]
    public interface SerecuWebServiceSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cedula_identidad del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatos", ReplyAction="*")]
        ServiceReferenceSerecu.ObtenerDatosResponse ObtenerDatos(ServiceReferenceSerecu.ObtenerDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceSerecu.ObtenerDatosResponse> ObtenerDatosAsync(ServiceReferenceSerecu.ObtenerDatosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cedula_identidad del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoDeNacimiento", ReplyAction="*")]
        ServiceReferenceSerecu.ObtenerCertificadoDeNacimientoResponse ObtenerCertificadoDeNacimiento(ServiceReferenceSerecu.ObtenerCertificadoDeNacimientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoDeNacimiento", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceSerecu.ObtenerCertificadoDeNacimientoResponse> ObtenerCertificadoDeNacimientoAsync(ServiceReferenceSerecu.ObtenerCertificadoDeNacimientoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cedula_identidad del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoDeMatrimonio", ReplyAction="*")]
        ServiceReferenceSerecu.ObtenerCertificadoDeMatrimonioResponse ObtenerCertificadoDeMatrimonio(ServiceReferenceSerecu.ObtenerCertificadoDeMatrimonioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoDeMatrimonio", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceSerecu.ObtenerCertificadoDeMatrimonioResponse> ObtenerCertificadoDeMatrimonioAsync(ServiceReferenceSerecu.ObtenerCertificadoDeMatrimonioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cedula_identidad del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoDeDefuncion", ReplyAction="*")]
        ServiceReferenceSerecu.ObtenerCertificadoDeDefuncionResponse ObtenerCertificadoDeDefuncion(ServiceReferenceSerecu.ObtenerCertificadoDeDefuncionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoDeDefuncion", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceSerecu.ObtenerCertificadoDeDefuncionResponse> ObtenerCertificadoDeDefuncionAsync(ServiceReferenceSerecu.ObtenerCertificadoDeDefuncionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatos", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceSerecu.ObtenerDatosRequestBody Body;
        
        public ObtenerDatosRequest()
        {
        }
        
        public ObtenerDatosRequest(ServiceReferenceSerecu.ObtenerDatosRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cedula_identidad;
        
        public ObtenerDatosRequestBody()
        {
        }
        
        public ObtenerDatosRequestBody(string cedula_identidad)
        {
            this.cedula_identidad = cedula_identidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceSerecu.ObtenerDatosResponseBody Body;
        
        public ObtenerDatosResponse()
        {
        }
        
        public ObtenerDatosResponse(ServiceReferenceSerecu.ObtenerDatosResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReferenceSerecu.Persona ObtenerDatosResult;
        
        public ObtenerDatosResponseBody()
        {
        }
        
        public ObtenerDatosResponseBody(ServiceReferenceSerecu.Persona ObtenerDatosResult)
        {
            this.ObtenerDatosResult = ObtenerDatosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoDeNacimientoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoDeNacimiento", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceSerecu.ObtenerCertificadoDeNacimientoRequestBody Body;
        
        public ObtenerCertificadoDeNacimientoRequest()
        {
        }
        
        public ObtenerCertificadoDeNacimientoRequest(ServiceReferenceSerecu.ObtenerCertificadoDeNacimientoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoDeNacimientoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cedula_identidad;
        
        public ObtenerCertificadoDeNacimientoRequestBody()
        {
        }
        
        public ObtenerCertificadoDeNacimientoRequestBody(string cedula_identidad)
        {
            this.cedula_identidad = cedula_identidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoDeNacimientoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoDeNacimientoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceSerecu.ObtenerCertificadoDeNacimientoResponseBody Body;
        
        public ObtenerCertificadoDeNacimientoResponse()
        {
        }
        
        public ObtenerCertificadoDeNacimientoResponse(ServiceReferenceSerecu.ObtenerCertificadoDeNacimientoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoDeNacimientoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReferenceSerecu.CertificadoDeNacimiento ObtenerCertificadoDeNacimientoResult;
        
        public ObtenerCertificadoDeNacimientoResponseBody()
        {
        }
        
        public ObtenerCertificadoDeNacimientoResponseBody(ServiceReferenceSerecu.CertificadoDeNacimiento ObtenerCertificadoDeNacimientoResult)
        {
            this.ObtenerCertificadoDeNacimientoResult = ObtenerCertificadoDeNacimientoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoDeMatrimonioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoDeMatrimonio", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceSerecu.ObtenerCertificadoDeMatrimonioRequestBody Body;
        
        public ObtenerCertificadoDeMatrimonioRequest()
        {
        }
        
        public ObtenerCertificadoDeMatrimonioRequest(ServiceReferenceSerecu.ObtenerCertificadoDeMatrimonioRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoDeMatrimonioRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cedula_identidad;
        
        public ObtenerCertificadoDeMatrimonioRequestBody()
        {
        }
        
        public ObtenerCertificadoDeMatrimonioRequestBody(string cedula_identidad)
        {
            this.cedula_identidad = cedula_identidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoDeMatrimonioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoDeMatrimonioResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceSerecu.ObtenerCertificadoDeMatrimonioResponseBody Body;
        
        public ObtenerCertificadoDeMatrimonioResponse()
        {
        }
        
        public ObtenerCertificadoDeMatrimonioResponse(ServiceReferenceSerecu.ObtenerCertificadoDeMatrimonioResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoDeMatrimonioResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReferenceSerecu.certificadoMatrimonio ObtenerCertificadoDeMatrimonioResult;
        
        public ObtenerCertificadoDeMatrimonioResponseBody()
        {
        }
        
        public ObtenerCertificadoDeMatrimonioResponseBody(ServiceReferenceSerecu.certificadoMatrimonio ObtenerCertificadoDeMatrimonioResult)
        {
            this.ObtenerCertificadoDeMatrimonioResult = ObtenerCertificadoDeMatrimonioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoDeDefuncionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoDeDefuncion", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceSerecu.ObtenerCertificadoDeDefuncionRequestBody Body;
        
        public ObtenerCertificadoDeDefuncionRequest()
        {
        }
        
        public ObtenerCertificadoDeDefuncionRequest(ServiceReferenceSerecu.ObtenerCertificadoDeDefuncionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoDeDefuncionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cedula_identidad;
        
        public ObtenerCertificadoDeDefuncionRequestBody()
        {
        }
        
        public ObtenerCertificadoDeDefuncionRequestBody(string cedula_identidad)
        {
            this.cedula_identidad = cedula_identidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoDeDefuncionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoDeDefuncionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceSerecu.ObtenerCertificadoDeDefuncionResponseBody Body;
        
        public ObtenerCertificadoDeDefuncionResponse()
        {
        }
        
        public ObtenerCertificadoDeDefuncionResponse(ServiceReferenceSerecu.ObtenerCertificadoDeDefuncionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoDeDefuncionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReferenceSerecu.CertificadoDefuncion ObtenerCertificadoDeDefuncionResult;
        
        public ObtenerCertificadoDeDefuncionResponseBody()
        {
        }
        
        public ObtenerCertificadoDeDefuncionResponseBody(ServiceReferenceSerecu.CertificadoDefuncion ObtenerCertificadoDeDefuncionResult)
        {
            this.ObtenerCertificadoDeDefuncionResult = ObtenerCertificadoDeDefuncionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface SerecuWebServiceSoapChannel : ServiceReferenceSerecu.SerecuWebServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class SerecuWebServiceSoapClient : System.ServiceModel.ClientBase<ServiceReferenceSerecu.SerecuWebServiceSoap>, ServiceReferenceSerecu.SerecuWebServiceSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SerecuWebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SerecuWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), SerecuWebServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SerecuWebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SerecuWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SerecuWebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SerecuWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SerecuWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceSerecu.ObtenerDatosResponse ServiceReferenceSerecu.SerecuWebServiceSoap.ObtenerDatos(ServiceReferenceSerecu.ObtenerDatosRequest request)
        {
            return base.Channel.ObtenerDatos(request);
        }
        
        public ServiceReferenceSerecu.Persona ObtenerDatos(string cedula_identidad)
        {
            ServiceReferenceSerecu.ObtenerDatosRequest inValue = new ServiceReferenceSerecu.ObtenerDatosRequest();
            inValue.Body = new ServiceReferenceSerecu.ObtenerDatosRequestBody();
            inValue.Body.cedula_identidad = cedula_identidad;
            ServiceReferenceSerecu.ObtenerDatosResponse retVal = ((ServiceReferenceSerecu.SerecuWebServiceSoap)(this)).ObtenerDatos(inValue);
            return retVal.Body.ObtenerDatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceSerecu.ObtenerDatosResponse> ServiceReferenceSerecu.SerecuWebServiceSoap.ObtenerDatosAsync(ServiceReferenceSerecu.ObtenerDatosRequest request)
        {
            return base.Channel.ObtenerDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceSerecu.ObtenerDatosResponse> ObtenerDatosAsync(string cedula_identidad)
        {
            ServiceReferenceSerecu.ObtenerDatosRequest inValue = new ServiceReferenceSerecu.ObtenerDatosRequest();
            inValue.Body = new ServiceReferenceSerecu.ObtenerDatosRequestBody();
            inValue.Body.cedula_identidad = cedula_identidad;
            return ((ServiceReferenceSerecu.SerecuWebServiceSoap)(this)).ObtenerDatosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceSerecu.ObtenerCertificadoDeNacimientoResponse ServiceReferenceSerecu.SerecuWebServiceSoap.ObtenerCertificadoDeNacimiento(ServiceReferenceSerecu.ObtenerCertificadoDeNacimientoRequest request)
        {
            return base.Channel.ObtenerCertificadoDeNacimiento(request);
        }
        
        public ServiceReferenceSerecu.CertificadoDeNacimiento ObtenerCertificadoDeNacimiento(string cedula_identidad)
        {
            ServiceReferenceSerecu.ObtenerCertificadoDeNacimientoRequest inValue = new ServiceReferenceSerecu.ObtenerCertificadoDeNacimientoRequest();
            inValue.Body = new ServiceReferenceSerecu.ObtenerCertificadoDeNacimientoRequestBody();
            inValue.Body.cedula_identidad = cedula_identidad;
            ServiceReferenceSerecu.ObtenerCertificadoDeNacimientoResponse retVal = ((ServiceReferenceSerecu.SerecuWebServiceSoap)(this)).ObtenerCertificadoDeNacimiento(inValue);
            return retVal.Body.ObtenerCertificadoDeNacimientoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceSerecu.ObtenerCertificadoDeNacimientoResponse> ServiceReferenceSerecu.SerecuWebServiceSoap.ObtenerCertificadoDeNacimientoAsync(ServiceReferenceSerecu.ObtenerCertificadoDeNacimientoRequest request)
        {
            return base.Channel.ObtenerCertificadoDeNacimientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceSerecu.ObtenerCertificadoDeNacimientoResponse> ObtenerCertificadoDeNacimientoAsync(string cedula_identidad)
        {
            ServiceReferenceSerecu.ObtenerCertificadoDeNacimientoRequest inValue = new ServiceReferenceSerecu.ObtenerCertificadoDeNacimientoRequest();
            inValue.Body = new ServiceReferenceSerecu.ObtenerCertificadoDeNacimientoRequestBody();
            inValue.Body.cedula_identidad = cedula_identidad;
            return ((ServiceReferenceSerecu.SerecuWebServiceSoap)(this)).ObtenerCertificadoDeNacimientoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceSerecu.ObtenerCertificadoDeMatrimonioResponse ServiceReferenceSerecu.SerecuWebServiceSoap.ObtenerCertificadoDeMatrimonio(ServiceReferenceSerecu.ObtenerCertificadoDeMatrimonioRequest request)
        {
            return base.Channel.ObtenerCertificadoDeMatrimonio(request);
        }
        
        public ServiceReferenceSerecu.certificadoMatrimonio ObtenerCertificadoDeMatrimonio(string cedula_identidad)
        {
            ServiceReferenceSerecu.ObtenerCertificadoDeMatrimonioRequest inValue = new ServiceReferenceSerecu.ObtenerCertificadoDeMatrimonioRequest();
            inValue.Body = new ServiceReferenceSerecu.ObtenerCertificadoDeMatrimonioRequestBody();
            inValue.Body.cedula_identidad = cedula_identidad;
            ServiceReferenceSerecu.ObtenerCertificadoDeMatrimonioResponse retVal = ((ServiceReferenceSerecu.SerecuWebServiceSoap)(this)).ObtenerCertificadoDeMatrimonio(inValue);
            return retVal.Body.ObtenerCertificadoDeMatrimonioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceSerecu.ObtenerCertificadoDeMatrimonioResponse> ServiceReferenceSerecu.SerecuWebServiceSoap.ObtenerCertificadoDeMatrimonioAsync(ServiceReferenceSerecu.ObtenerCertificadoDeMatrimonioRequest request)
        {
            return base.Channel.ObtenerCertificadoDeMatrimonioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceSerecu.ObtenerCertificadoDeMatrimonioResponse> ObtenerCertificadoDeMatrimonioAsync(string cedula_identidad)
        {
            ServiceReferenceSerecu.ObtenerCertificadoDeMatrimonioRequest inValue = new ServiceReferenceSerecu.ObtenerCertificadoDeMatrimonioRequest();
            inValue.Body = new ServiceReferenceSerecu.ObtenerCertificadoDeMatrimonioRequestBody();
            inValue.Body.cedula_identidad = cedula_identidad;
            return ((ServiceReferenceSerecu.SerecuWebServiceSoap)(this)).ObtenerCertificadoDeMatrimonioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceSerecu.ObtenerCertificadoDeDefuncionResponse ServiceReferenceSerecu.SerecuWebServiceSoap.ObtenerCertificadoDeDefuncion(ServiceReferenceSerecu.ObtenerCertificadoDeDefuncionRequest request)
        {
            return base.Channel.ObtenerCertificadoDeDefuncion(request);
        }
        
        public ServiceReferenceSerecu.CertificadoDefuncion ObtenerCertificadoDeDefuncion(string cedula_identidad)
        {
            ServiceReferenceSerecu.ObtenerCertificadoDeDefuncionRequest inValue = new ServiceReferenceSerecu.ObtenerCertificadoDeDefuncionRequest();
            inValue.Body = new ServiceReferenceSerecu.ObtenerCertificadoDeDefuncionRequestBody();
            inValue.Body.cedula_identidad = cedula_identidad;
            ServiceReferenceSerecu.ObtenerCertificadoDeDefuncionResponse retVal = ((ServiceReferenceSerecu.SerecuWebServiceSoap)(this)).ObtenerCertificadoDeDefuncion(inValue);
            return retVal.Body.ObtenerCertificadoDeDefuncionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceSerecu.ObtenerCertificadoDeDefuncionResponse> ServiceReferenceSerecu.SerecuWebServiceSoap.ObtenerCertificadoDeDefuncionAsync(ServiceReferenceSerecu.ObtenerCertificadoDeDefuncionRequest request)
        {
            return base.Channel.ObtenerCertificadoDeDefuncionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceSerecu.ObtenerCertificadoDeDefuncionResponse> ObtenerCertificadoDeDefuncionAsync(string cedula_identidad)
        {
            ServiceReferenceSerecu.ObtenerCertificadoDeDefuncionRequest inValue = new ServiceReferenceSerecu.ObtenerCertificadoDeDefuncionRequest();
            inValue.Body = new ServiceReferenceSerecu.ObtenerCertificadoDeDefuncionRequestBody();
            inValue.Body.cedula_identidad = cedula_identidad;
            return ((ServiceReferenceSerecu.SerecuWebServiceSoap)(this)).ObtenerCertificadoDeDefuncionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SerecuWebServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SerecuWebServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SerecuWebServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50984/SerecuWebService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SerecuWebServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50984/SerecuWebService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SerecuWebServiceSoap,
            
            SerecuWebServiceSoap12,
        }
    }
}
