//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servicioSegip
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Datos", Namespace="http://tempuri.org/")]
    public partial class Datos : object
    {
        
        private string ciField;
        
        private string nombresField;
        
        private string primerApellidoField;
        
        private string segundoApellidoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ci
        {
            get
            {
                return this.ciField;
            }
            set
            {
                this.ciField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombres
        {
            get
            {
                return this.nombresField;
            }
            set
            {
                this.nombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string primerApellido
        {
            get
            {
                return this.primerApellidoField;
            }
            set
            {
                this.primerApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string segundoApellido
        {
            get
            {
                return this.segundoApellidoField;
            }
            set
            {
                this.segundoApellidoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="servicioSegip.SegipServiceSoap")]
    public interface SegipServiceSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ci del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarDatos", ReplyAction="*")]
        servicioSegip.VerificarDatosResponse VerificarDatos(servicioSegip.VerificarDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<servicioSegip.VerificarDatosResponse> VerificarDatosAsync(servicioSegip.VerificarDatosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ci del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerDatos", ReplyAction="*")]
        servicioSegip.obtenerDatosResponse obtenerDatos(servicioSegip.obtenerDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<servicioSegip.obtenerDatosResponse> obtenerDatosAsync(servicioSegip.obtenerDatosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarDatosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarDatos", Namespace="http://tempuri.org/", Order=0)]
        public servicioSegip.VerificarDatosRequestBody Body;
        
        public VerificarDatosRequest()
        {
        }
        
        public VerificarDatosRequest(servicioSegip.VerificarDatosRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarDatosRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ci;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string primerApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string segundoApellido;
        
        public VerificarDatosRequestBody()
        {
        }
        
        public VerificarDatosRequestBody(string ci, string nombres, string primerApellido, string segundoApellido)
        {
            this.ci = ci;
            this.nombres = nombres;
            this.primerApellido = primerApellido;
            this.segundoApellido = segundoApellido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarDatosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarDatosResponse", Namespace="http://tempuri.org/", Order=0)]
        public servicioSegip.VerificarDatosResponseBody Body;
        
        public VerificarDatosResponse()
        {
        }
        
        public VerificarDatosResponse(servicioSegip.VerificarDatosResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarDatosResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerificarDatosResult;
        
        public VerificarDatosResponseBody()
        {
        }
        
        public VerificarDatosResponseBody(bool VerificarDatosResult)
        {
            this.VerificarDatosResult = VerificarDatosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerDatosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerDatos", Namespace="http://tempuri.org/", Order=0)]
        public servicioSegip.obtenerDatosRequestBody Body;
        
        public obtenerDatosRequest()
        {
        }
        
        public obtenerDatosRequest(servicioSegip.obtenerDatosRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerDatosRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ci;
        
        public obtenerDatosRequestBody()
        {
        }
        
        public obtenerDatosRequestBody(string ci)
        {
            this.ci = ci;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerDatosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerDatosResponse", Namespace="http://tempuri.org/", Order=0)]
        public servicioSegip.obtenerDatosResponseBody Body;
        
        public obtenerDatosResponse()
        {
        }
        
        public obtenerDatosResponse(servicioSegip.obtenerDatosResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerDatosResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public servicioSegip.Datos obtenerDatosResult;
        
        public obtenerDatosResponseBody()
        {
        }
        
        public obtenerDatosResponseBody(servicioSegip.Datos obtenerDatosResult)
        {
            this.obtenerDatosResult = obtenerDatosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface SegipServiceSoapChannel : servicioSegip.SegipServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class SegipServiceSoapClient : System.ServiceModel.ClientBase<servicioSegip.SegipServiceSoap>, servicioSegip.SegipServiceSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SegipServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SegipServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), SegipServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SegipServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SegipServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SegipServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SegipServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SegipServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        servicioSegip.VerificarDatosResponse servicioSegip.SegipServiceSoap.VerificarDatos(servicioSegip.VerificarDatosRequest request)
        {
            return base.Channel.VerificarDatos(request);
        }
        
        public bool VerificarDatos(string ci, string nombres, string primerApellido, string segundoApellido)
        {
            servicioSegip.VerificarDatosRequest inValue = new servicioSegip.VerificarDatosRequest();
            inValue.Body = new servicioSegip.VerificarDatosRequestBody();
            inValue.Body.ci = ci;
            inValue.Body.nombres = nombres;
            inValue.Body.primerApellido = primerApellido;
            inValue.Body.segundoApellido = segundoApellido;
            servicioSegip.VerificarDatosResponse retVal = ((servicioSegip.SegipServiceSoap)(this)).VerificarDatos(inValue);
            return retVal.Body.VerificarDatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<servicioSegip.VerificarDatosResponse> servicioSegip.SegipServiceSoap.VerificarDatosAsync(servicioSegip.VerificarDatosRequest request)
        {
            return base.Channel.VerificarDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<servicioSegip.VerificarDatosResponse> VerificarDatosAsync(string ci, string nombres, string primerApellido, string segundoApellido)
        {
            servicioSegip.VerificarDatosRequest inValue = new servicioSegip.VerificarDatosRequest();
            inValue.Body = new servicioSegip.VerificarDatosRequestBody();
            inValue.Body.ci = ci;
            inValue.Body.nombres = nombres;
            inValue.Body.primerApellido = primerApellido;
            inValue.Body.segundoApellido = segundoApellido;
            return ((servicioSegip.SegipServiceSoap)(this)).VerificarDatosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        servicioSegip.obtenerDatosResponse servicioSegip.SegipServiceSoap.obtenerDatos(servicioSegip.obtenerDatosRequest request)
        {
            return base.Channel.obtenerDatos(request);
        }
        
        public servicioSegip.Datos obtenerDatos(string ci)
        {
            servicioSegip.obtenerDatosRequest inValue = new servicioSegip.obtenerDatosRequest();
            inValue.Body = new servicioSegip.obtenerDatosRequestBody();
            inValue.Body.ci = ci;
            servicioSegip.obtenerDatosResponse retVal = ((servicioSegip.SegipServiceSoap)(this)).obtenerDatos(inValue);
            return retVal.Body.obtenerDatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<servicioSegip.obtenerDatosResponse> servicioSegip.SegipServiceSoap.obtenerDatosAsync(servicioSegip.obtenerDatosRequest request)
        {
            return base.Channel.obtenerDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<servicioSegip.obtenerDatosResponse> obtenerDatosAsync(string ci)
        {
            servicioSegip.obtenerDatosRequest inValue = new servicioSegip.obtenerDatosRequest();
            inValue.Body = new servicioSegip.obtenerDatosRequestBody();
            inValue.Body.ci = ci;
            return ((servicioSegip.SegipServiceSoap)(this)).obtenerDatosAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SegipServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SegipServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SegipServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:64543/SegipService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SegipServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:64543/SegipService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SegipServiceSoap,
            
            SegipServiceSoap12,
        }
    }
}
